devices:
  heatbox:
    keys:
      power: KEY_POWER 
      toggle_low_high: KEY_1 
      raise_temperature: KEY_2 
      toggle_oscillation: KEY_3 
      set_timer: KEY_4 
      lower_temperature: KEY_5 
    temperature_settings:
      offset_toggles: 10
      degrees_on_above_nest: 2
      highest_degree: 90
      lowest_degree: 39
      too_hot: 74
      forced_time_on:
        start: 7
        stop: 9
  oil_heater:
    keys:
      power: KEY_POWER
      raise_temperature: KEY_2
      lower_temperature: KEY_3
    temperature_settings:
      too_hot: 74
      offset_toggles: 1
      degrees_on_above_nest: 4
      highest_degree: 95
      lowest_degree: 42
  magic_mirror:
    keys:
      enter: KEY_ENTER
      power: KEY_POWER
      right: KEY_RIGHT
      left: KEY_LEFT
      up: KEY_UP
      down: KEY_DOWN
      back: KEY_BACK
      setup: KEY_SETUP
    cec_controls:
      power_on: 'on 0'
      power_off: 'standby 0'
    brightness_levels:
      -
        after: 1000
        level: 30
      -
        after: 1400
        level: 45
      -
        after: 1500
        level: 60
      -
        after: 2300
        level: 20
   
api:
  open_weather:
    options:
      :units: imperial
